api_platform:
    show_webby: false
    title: 'NUTRITION PROJECT'
    description: 'An Api to manage recipe and patient'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header
